# setting for training UColor with Ranker loss

dataset:
    dataset_name : UIEBD
    root : ../data/UIEBD/
    crop_size: 256
    train_batchsize : 4
    val_batchsize : 1
    num_workers : 2
    crop_size : 256

model:
    # model_name: NU2Net
    resume_ckpt_path: 
    cuda: true
    parallel: false
    basic_channel: 64

train:
    # basic hyper parameters setting
    start_epoch: 0
    epoch: 1000
    lr: 2.0e-4
    optimizer: Adam
    lr_scheduler: CosineAnnealingLR
    lr_scheduler_arg: {T_max : 1000}

    # loss setting
    loss_vgg: false
    loss_rank: true
    loss_coff: [1, 0.0, 0.025]

    ranker_args:
        model_name: MyCoaT
        resume_ckpt_path: ranker_output/MyCoaT/dynamic/checkpoints/checkpoint_100best.pth
        cuda: true
        parallel: false
        patch_size: 4
        embed_dims: [152, 320, 320, 320]
        serial_depths: [2, 2, 2, 2]
        parallel_depth: 6
        num_heads: 8
        mlp_ratios: [4, 4, 4, 4]
        add_historgram: true
        his_channel: 192
        connect_type: dynamic
    
experiments:
    save_path: ./model/ckpt/
    log_dir: ./model/log
    checkpoints: checkpoints
    results: results

test:
    start_epoch: 0
    end_epoch: 1
    test_ckpt_path:
    save_img: false